### ISSUE TITLE
Je ne fais que passer

### ISSUE THREAD

**Issue by vict0rsch** [regardscitoyens/NosDeputes2-front#16]
Hello,

Je testais la fonction "For You" de Github et un pattern de PR/Issue-naming a attiré mon attention au milieu de ce feed.

Je ne pense pas que vous soyez cyniques au point d'avoir fait exprès. Mais avez vous pensé à la proximité sonore et même littérale entre `feat(deputes)` et `fils de...`? 

C'est ma contribution aujourd'hui. À bon entendeur 🙃

**Comment by implicitdef** [comment]
Ce n'est pas notre intention. Les gens qui s'intéressent à ce repo ont le contexte et savent que `feat(deputes)` parle de "députés".
