### ISSUE TITLE
bug: Error: Couldn't find latest group... (sur l'ancienne législature)

### ISSUE THREAD

**Issue by implicitdef** [regardscitoyens/NosDeputes2-front#19]
En me branchant sur un dump de l'ancienne législature, en allant sur http://localhost:3000/deputes, la page explose avec :

```Error: Couldn't find latest group for depute 633```

**Comment by revolunet** [comment]
il y a 4 députés dans ce cas : elisabeth-marquet, sarah-taillebois, carine-sinai-bossou, brigitte-klinkert

**Comment by implicitdef** [comment]
ah, intéressant, ce sont tous des députés suppléants qui ont dû remplacer leur député un jour, et qui ont immédiatement démissionné. Techniquement l'assemblée considère qu'ils ont été députés. On pourrait se demander si c'est pertinent de les afficher. Je suis OK pour juste faire fonctionner tel quel pour le moment.
